source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'Hex'

pod 'Hue', path: '../../'
pod 'Imaginary', git: 'https://github.com/hyperoslo/Imaginary', :branch => 'swift-3'
pod 'Cache', git: 'https://github.com/hyperoslo/Cache', :branch => 'swift-3'
pod 'Spots', git: 'https://github.com/hyperoslo/Spots', :branch => 'swift-3'
pod 'Brick', git: 'https://github.com/hyperoslo/Brick', :branch => 'swift-3'
pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar', :branch => 'swift-3'
pod 'Tailor', '2.0.0'
